language: csharp

sudo: true

before_script:
 - chmod +x ./build.sh
 - sudo mkdir /etc/mono/registry
 - sudo chmod uog+rw /etc/mono/registry

script: 
  - ./build.sh RunTests && ./build.sh DeployToCloud
