language: csharp

sudo: true  # use the new container-based Travis infrastructure

before_script:
 - chmod +x ./build.sh
 - chmod uog+rw /etc/mono/registry

script: 
  - ./build.sh RunTests && ./build.sh DeployToCloud
